version: '2.2'
services:
  shard-a:
    scale: 3
    image: mongo:4
    command: ["--shardsvr", "--replSet", "rs-shard-a"]
    volumes:
     - ./shard-a-init:/shard-a-init
  shard-b:
    scale: 3
    image: mongo:4
    command: ["--shardsvr", "--replSet", "rs-shard-b"]
    volumes:
     - ./shard-b-init:/shard-b-init
  config-server:
    scale: 3
    image: mongo:4
    command: ["--configsvr", "--replSet", "rs-conf"]
    volumes:
     - ./config-server-init:/config-server-init
  mongos:
    scale: 2
    image: mongo:4
    command: ["mongos", "--configdb", "rs-conf/mongo-sharded-cluster-docker_config-server_1:27019,mongo-sharded-cluster-docker_config-server_2:27019,mongo-sharded-cluster-docker_config-server_3:27019"]
    volumes:
     - ./router-init:/router-init
     - ./init-data:/init-data
    depends_on:
     - config-server